# RAG Assignment: Baseline Retrieval vs. Cross-Encoder Re-Ranking

## 1. Environment Setup and Configuration

This notebook compares two Retrieval-Augmented Generation (RAG) pipelines using a constitutional law PDF.

- **Pipeline 1 — Baseline:** Retrieve the Top 10 chunks using dense vector similarity and select the Top 3.
- **Pipeline 2 — Re-ranking:** Retrieve the same Top 10 chunks, re-rank them using a Cross-Encoder, and select the new Top 3.

Both pipelines use the same PDF, queries, and answer-generation prompt. We compare their retrieval rankings, generated answers, and execution times.

In [47]:
from pathlib import Path
import sys
import torch
import pymupdf
import faiss
import pandas as pd
import numpy as np

PROJECT_DIR = Path.cwd()
DATA_DIR = PROJECT_DIR / "data"
OUTPUT_DIR = PROJECT_DIR / "outputs"

PDF_FILES = list(DATA_DIR.glob("*.pdf"))

print("Python executable:", sys.executable)
print("Project directory:", PROJECT_DIR)
print("Device: CPU")
print("CUDA available:", torch.cuda.is_available())
print("PDF files found:", [p.name for p in PDF_FILES])

OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

assert len(PDF_FILES) > 0, (
    "No PDF found. Place your constitutional law PDF inside the data folder."
)

PDF_PATH = PDF_FILES[0]
print("\nSelected PDF:", PDF_PATH.name)
print("Environment setup completed.")

Python executable: c:\Users\HP\Downloads\LMA_Assignment1\lma_env\Scripts\python.exe
Project directory: c:\Users\HP\Downloads\LMA_Assignment1
Device: CPU
CUDA available: False
PDF files found: ['OJ_L_202401689_EN_TXT.pdf']

Selected PDF: OJ_L_202401689_EN_TXT.pdf
Environment setup completed.

## 2. PDF Loading and Text Extraction

This section extracts text from each page of the EU AI Act PDF. We preserve page numbers so that retrieved chunks can be traced back to their source pages.

In [48]:
import pymupdf

with pymupdf.open(PDF_PATH) as pdf:
    for i in [0, 1, 2]:
        page = pdf[i]
        text = page.get_text("text").strip()

        print(f"\nPage {i + 1}")
        print("Extracted characters:", len(text))
        print("Embedded images:", len(page.get_images(full=True)))
        print("Text preview:", repr(text[:300]))

Page 1
Extracted characters: 3599
Embedded images: 1
Text preview: 'REGULATION (EU) 2024/1689 OF THE EUROPEAN PARLIAMENT AND OF THE COUNCIL\nof 13 June 2024\nlaying down harmonised rules on artificial intelligence and amending Regulations (EC) No 300/2008, \n(EU) No 167/2013, (EU) No 168/2013, (EU) 2018/858, (EU) 2018/1139 and (EU) 2019/2144 and \nDirectives 2014/90/EU,'

Page 2
Extracted characters: 5130
Embedded images: 0
Text preview: 'guaranteeing the uniform protection of overriding reasons of public interest and of rights of persons throughout the \ninternal market on the basis of Article 114 of the Treaty on the Functioning of the European Union (TFEU). To the \nextent that this Regulation contains specific rules on the protecti'

Page 3
Extracted characters: 6884
Embedded images: 0
Text preview: '(9)\nHarmonised rules applicable to the placing on the market, the putting into service and the use of high-risk AI \nsystems should be laid down consistently with Regulation (EC) No 765/2008 of the European Parliament and of the \nCouncil (7), Decision No 768/2008/EC of the European Parliament and of '

In [49]:
pages = []

with pymupdf.open(PDF_PATH) as pdf:
    total_pdf_pages = len(pdf)

    for page_num, page in enumerate(pdf, start=1):
        text = page.get_text("text").strip()

        if text:
            pages.append({
                "page_number": page_num,
                "text": text
            })

print("Total PDF pages:", total_pdf_pages)
print("Pages with extractable text:", len(pages))
print("Total extracted characters:", sum(len(p["text"]) for p in pages))

print("\nFirst page preview:\n")
print(pages[0]["text"][:1000] if pages else "No text extracted.")

Total PDF pages: 144
Pages with extractable text: 144
Total extracted characters: 599631

First page preview:

REGULATION (EU) 2024/1689 OF THE EUROPEAN PARLIAMENT AND OF THE COUNCIL
of 13 June 2024
laying down harmonised rules on artificial intelligence and amending Regulations (EC) No 300/2008,
(EU) No 167/2013, (EU) No 168/2013, (EU) 2018/858, (EU) 2018/1139 and (EU) 2019/2144 and
Directives 2014/90/EU, (EU) 2016/797 and (EU) 2020/1828 (Artificial Intelligence Act)
(Text with EEA relevance)
THE EUROPEAN PARLIAMENT AND THE COUNCIL OF THE EUROPEAN UNION,
Having regard to the Treaty on the Functioning of the European Union, and in particular Articles 16 and 114 thereof,
Having regard to the proposal from the European Commission,
After transmission of the draft legislative act to the national parliaments,
Having regard to the opinion of the European Economic and Social Committee (1),
Having regard to the opinion of the European Central Bank (2),
Having regard to the opinion of the Committee of the Regions (3),
Acting in accordance with the ordinary legislative procedure (4),
Whereas:
(1)
The p

### 2.1. Extracted Text Quality Assessment

Before building the retrieval index, inspect the extracted pages for empty content, unusually short pages, repeated headers, and formatting artifacts. Since this is a legal document, preserve article numbers, section headings, exceptions, and references.

In [50]:
import pandas as pd
import re

page_df = pd.DataFrame(pages)

page_df["character_count"] = page_df["text"].str.len()
page_df["word_count"] = page_df["text"].str.split().str.len()

print("Total pages:", len(page_df))
print("Empty pages:", (page_df["character_count"] == 0).sum())
print("\nCharacter count summary:")
print(page_df["character_count"].describe())
print("\nWord count summary:")
print(page_df["word_count"].describe())

print("\nShortest 10 pages:")
print(
    page_df[["page_number", "character_count", "word_count"]]
    .sort_values("character_count")
    .head(10)
    .to_string(index=False)
)

Total pages: 144
Empty pages: 0

Character count summary:
count     144.000000
mean     4164.104167
std      1330.156690
min       254.000000
25%      3486.250000
50%      4058.000000
75%      5327.750000
max      6884.000000
Name: character_count, dtype: float64

Word count summary:
count     144.000000
mean      634.868056
std       199.779187
min        33.000000
25%       528.500000
50%       623.500000
75%       797.250000
max      1065.000000
Name: word_count, dtype: float64

Shortest 10 pages:
 page_number  character_count  word_count
         142              254          33
         129              493          76
         133              807         120
         137              936         150
         126              953         137
         138              979         154
         140             1384         198
         132             1504         237
         144             1587         249
         143             1617         254

### 2.2. PDF Text Preprocessing

PDF extraction can introduce formatting artifacts, including standalone page numbers, repeated headers and footers, excessive whitespace, and words split across lines. This section cleans formatting while preserving legal provisions, article numbers, paragraph numbering, and cross-references.

In [51]:
for page in pages[:5]:
    lines = page["text"].splitlines()

    print(f"\n--- Page {page['page_number']} ---")
    print("First 5 lines:", lines[:5])
    print("Last 5 lines:", lines[-5:])

--- Page 1 ---
First 5 lines: ['REGULATION (EU) 2024/1689 OF THE EUROPEAN PARLIAMENT AND OF THE COUNCIL', 'of 13 June 2024', 'laying down harmonised rules on artificial intelligence and amending Regulations (EC) No 300/2008, ', '(EU) No 167/2013, (EU) No 168/2013, (EU) 2018/858, (EU) 2018/1139 and (EU) 2019/2144 and ', 'Directives 2014/90/EU, (EU) 2016/797 and (EU) 2020/1828 (Artificial Intelligence Act)']
Last 5 lines: ['(3)', 'OJ C 97, 28.2.2022, p. 60.', '(4)', 'Position of the European Parliament of 13 March 2024 (not yet published in the Official Journal) and decision of the Council of ', '21 May 2024.']

--- Page 2 ---
First 5 lines: ['guaranteeing the uniform protection of overriding reasons of public interest and of rights of persons throughout the ', 'internal market on the basis of Article 114 of the Treaty on the Functioning of the European Union (TFEU). To the ', 'extent that this Regulation contains specific rules on the protection of individuals with regard to the processing of ', 'personal data concerning restrictions of the use of AI systems for remote biometric identification for the purpose of ', 'law enforcement, of the use of AI systems for risk assessments of natural persons for the purpose of law ']
Last 5 lines: ['(5)', 'European Council, Special meeting of the European Council (1 and 2 October 2020) — Conclusions, EUCO 13/20, 2020, p. 6.', '(6)', 'European Parliament resolution of 20 October 2020 with recommendations to the Commission on a framework of ethical aspects ', 'of artificial intelligence, robotics and related technologies, 2020/2012(INL).']

--- Page 3 ---
First 5 lines: ['(9)', 'Harmonised rules applicable to the placing on the market, the putting into service and the use of high-risk AI ', 'systems should be laid down consistently with Regulation (EC) No 765/2008 of the European Parliament and of the ', 'Council (7), Decision No 768/2008/EC of the European Parliament and of the Council (8) and Regulation (EU) ', '2019/1020 of the European Parliament and of the Council (9) (New Legislative Framework). The harmonised rules ']
Last 5 lines: ['Council Framework Decision 2008/977/JHA (OJ L 119, 4.5.2016, p. 89).', '(14)', 'Directive 2002/58/EC of the European Parliament and of the Council of 12 July 2002 concerning the processing of personal data ', 'and the protection of privacy in the electronic communications sector (Directive on privacy and electronic communications) (OJ ', 'L 201, 31.7.2002, p. 37).']

--- Page 4 ---
First 5 lines: ['rights and guarantees awarded to them by such Union law, including the rights related to solely automated individual ', 'decision-making, including profiling. Harmonised rules for the placing on the market, the putting into service and ', 'the use of AI systems established under this Regulation should facilitate the effective implementation and enable the ', 'exercise of the data subjects’ rights and other remedies guaranteed under Union law on the protection of personal ', 'data and of other fundamental rights.']
Last 5 lines: ['4/144', 'ELI: http://data.europa.eu/eli/reg/2024/1689/oj', '(15)', 'Regulation (EU) 2022/2065 of the European Parliament and of the Council of 19 October 2022 on a Single Market For Digital ', 'Services and amending Directive 2000/31/EC (Digital Services Act) (OJ L 277, 27.10.2022, p. 1).']

--- Page 5 ---
First 5 lines: ['(16)', 'The notion of ‘biometric categorisation’ referred to in this Regulation should be defined as assigning natural persons ', 'to specific categories on the basis of their biometric data. Such specific categories can relate to aspects such as sex, ', 'age, hair colour, eye colour, tattoos, behavioural or personality traits, language, religion, membership of a national ', 'minority, sexual or political orientation. This does not include biometric categorisation systems that are a purely ']
Last 5 lines: ['through either Union or national law directly related to public safety or security or through the clear manifestation ', 'OJ L, 12.7.2024', 'EN', 'ELI: http://data.europa.eu/eli/reg/2024/1689/oj', '5/144']

In [52]:
import re

def clean_page_text(text):
    cleaned_lines = []

    for line in text.splitlines():
        line = line.strip()

        if not line:
            continue

        # Remove standalone page numbers, not numbered legal clauses.
        if re.fullmatch(r"\d{1,3}", line):
            continue

        cleaned_lines.append(line)

    text = "\n".join(cleaned_lines)
    text = text.replace("\u00ad", "")  # Soft hyphen
    text = text.replace("\x00", "")    # Null character
    text = re.sub(r"[ \t]+", " ", text)
    text = re.sub(r"\n{3,}", "\n\n", text)

    return text.strip()


cleaned_pages = [
    {
        "page_number": page["page_number"],
        "text": clean_page_text(page["text"])
    }
    for page in pages
]

print("Pages before cleaning:", len(pages))
print("Pages after cleaning:", len(cleaned_pages))
print("Characters before:", sum(len(p["text"]) for p in pages))
print("Characters after:", sum(len(p["text"]) for p in cleaned_pages))

Pages before cleaning: 144
Pages after cleaning: 144
Characters before: 599631
Characters after: 595562

In [53]:

for page in cleaned_pages[:2]:
    print(f"\n--- Cleaned Page {page['page_number']} ---")
    print(page["text"][:1200])

--- Cleaned Page 1 ---
REGULATION (EU) 2024/1689 OF THE EUROPEAN PARLIAMENT AND OF THE COUNCIL
of 13 June 2024
laying down harmonised rules on artificial intelligence and amending Regulations (EC) No 300/2008,
(EU) No 167/2013, (EU) No 168/2013, (EU) 2018/858, (EU) 2018/1139 and (EU) 2019/2144 and
Directives 2014/90/EU, (EU) 2016/797 and (EU) 2020/1828 (Artificial Intelligence Act)
(Text with EEA relevance)
THE EUROPEAN PARLIAMENT AND THE COUNCIL OF THE EUROPEAN UNION,
Having regard to the Treaty on the Functioning of the European Union, and in particular Articles 16 and 114 thereof,
Having regard to the proposal from the European Commission,
After transmission of the draft legislative act to the national parliaments,
Having regard to the opinion of the European Economic and Social Committee (1),
Having regard to the opinion of the European Central Bank (2),
Having regard to the opinion of the Committee of the Regions (3),
Acting in accordance with the ordinary legislative procedure (4),
Whereas:
(1)
The purpose of this Regulation is to improve the functioning of the internal market by laying down a uniform legal
framework in particular for the development, the placing on the market, the putting into ser

--- Cleaned Page 2 ---
guaranteeing the uniform protection of overriding reasons of public interest and of rights of persons throughout the
internal market on the basis of Article 114 of the Treaty on the Functioning of the European Union (TFEU). To the
extent that this Regulation contains specific rules on the protection of individuals with regard to the processing of
personal data concerning restrictions of the use of AI systems for remote biometric identification for the purpose of
law enforcement, of the use of AI systems for risk assessments of natural persons for the purpose of law
enforcement and of the use of AI systems of biometric categorisation for the purpose of law enforcement, it is
appropriate to base this Regulation, in so far as those specific rules are concerned, on Article 16 TFEU. In light of
those specific rules and the recourse to Article 16 TFEU, it is appropriate to consult the European Data Protection
Board.
(4)
AI is a fast evolving family of technologies that contributes to a wide array of economic, environmental and societal
benefits across the entire spectrum of industries and social activities. By improving prediction, optimising operations
and resource allocation, and perso

## 3. Text Chunking and Metadata

The extracted document is divided into overlapping chunks. Each chunk retains its unique ID and source page number, allowing retrieved passages to be traced back to the original PDF.

In [54]:
def make_chunks(pages, chunk_size=450, overlap=80):
    chunks = []
    chunk_id = 0

    for page in pages:
        words = page["text"].split()
        start = 0

        while start < len(words):
            end = min(start + chunk_size, len(words))

            chunks.append({
                "chunk_id": chunk_id,
                "page_number": page["page_number"],
                "text": " ".join(words[start:end])
            })

            chunk_id += 1

            if end == len(words):
                break

            start = end - overlap

    return chunks


chunks = make_chunks(cleaned_pages)

print("Total chunks:", len(chunks))
print("Unique chunk IDs:", len(set(c["chunk_id"] for c in chunks)))
print("Empty chunks:", sum(not c["text"].strip() for c in chunks))
print("Pages represented:", len(set(c["page_number"] for c in chunks)))

print("\nFirst chunk:\n")
print(chunks[0]["text"][:1000])

Total chunks: 300
Unique chunk IDs: 300
Empty chunks: 0
Pages represented: 144

First chunk:

REGULATION (EU) 2024/1689 OF THE EUROPEAN PARLIAMENT AND OF THE COUNCIL of 13 June 2024 laying down harmonised rules on artificial intelligence and amending Regulations (EC) No 300/2008, (EU) No 167/2013, (EU) No 168/2013, (EU) 2018/858, (EU) 2018/1139 and (EU) 2019/2144 and Directives 2014/90/EU, (EU) 2016/797 and (EU) 2020/1828 (Artificial Intelligence Act) (Text with EEA relevance) THE EUROPEAN PARLIAMENT AND THE COUNCIL OF THE EUROPEAN UNION, Having regard to the Treaty on the Functioning of the European Union, and in particular Articles 16 and 114 thereof, Having regard to the proposal from the European Commission, After transmission of the draft legislative act to the national parliaments, Having regard to the opinion of the European Economic and Social Committee (1), Having regard to the opinion of the European Central Bank (2), Having regard to the opinion of the Committee of the Regions (3), Acting in accordance with the ordinary legislative procedure (4), Whereas: (1) The pur

## 4. Baseline Retrieval: Bi-Encoder and FAISS

The `BAAI/bge-base-en-v1.5` embedding model encodes each chunk independently into a dense vector. We normalize the vectors and use FAISS inner-product search, which is equivalent to cosine similarity for normalized vectors.

In [55]:
from sentence_transformers import SentenceTransformer
import numpy as np
import faiss

DEVICE = "cpu"
TOP_K = 10
FINAL_K = 3

embedding_model = SentenceTransformer(
    "BAAI/bge-base-en-v1.5",
    device=DEVICE
)

print("Embedding model loaded:", "BAAI/bge-base-en-v1.5")

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

Embedding model loaded: BAAI/bge-base-en-v1.5

In [56]:
chunk_texts = [chunk["text"] for chunk in chunks]

embeddings = embedding_model.encode(
    chunk_texts,
    batch_size=16,
    convert_to_numpy=True,
    normalize_embeddings=True,
    show_progress_bar=True
).astype("float32")

index = faiss.IndexFlatIP(embeddings.shape[1])
index.add(embeddings)

print("Embedding matrix shape:", embeddings.shape)
print("Vectors indexed:", index.ntotal)

print("Vector dimensions:", embeddings.shape[1])

Batches:   0%|          | 0/19 [00:00<?, ?it/s]

Embedding matrix shape: (300, 768)
Vectors indexed: 300
Vector dimensions: 768

In [57]:
def retrieve_top10(query):
    query_text = (
        "Represent this sentence for searching relevant passages: " + query
    )

    query_embedding = embedding_model.encode(
        [query_text],
        convert_to_numpy=True,
        normalize_embeddings=True
    ).astype("float32")

    scores, indices = index.search(query_embedding, TOP_K)

    results = []

    for rank, (idx, score) in enumerate(
        zip(indices[0], scores[0]), start=1
    ):
        if idx < 0:
            continue

        results.append({
            **chunks[int(idx)],
            "initial_rank": rank,
            "bi_score": float(score)
        })

    return results

In [58]:
query = "What obligations apply to providers of high-risk AI systems?"

baseline_results = retrieve_top10(query)

for item in baseline_results:
    print(
        f"Rank: {item['initial_rank']} | "
        f"Page: {item['page_number']} | "
        f"Score: {item['bi_score']:.4f}"
    )
    print(item["text"][:350])
    print("-" * 80)

Rank: 1 | Page: 62 | Score: 0.8099
SECTION 3 Obligations of providers and deployers of high-risk AI systems and other parties Article 16 Obligations of providers of high-risk AI systems Providers of high-risk AI systems shall: (a) ensure that their high-risk AI systems are compliant with the requirements set out in Section 2; (b) indicate on the high-risk AI system or, where that is
--------------------------------------------------------------------------------
Rank: 2 | Page: 67 | Score: 0.7815
Article 25 Responsibilities along the AI value chain 1. Any distributor, importer, deployer or other third-party shall be considered to be a provider of a high-risk AI system for the purposes of this Regulation and shall be subject to the obligations of the provider under Article 16, in any of the following circumstances: (a) they put their name or
--------------------------------------------------------------------------------
Rank: 3 | Page: 56 | Score: 0.7579
2. Where a product contains an AI system, to which the requirements of this Regulation as well as requirements of the Union harmonisation legislation listed in Section A of Annex I apply, providers shall be responsible for ensuring that their product is fully compliant with all applicable requirements under applicable Union harmonisation legislatio
--------------------------------------------------------------------------------
Rank: 4 | Page: 24 | Score: 0.7532
services but also components or processes that are incorporated by the provider into the AI system with various objectives, including the model training, model retraining, model testing and evaluation, integration into software, or other aspects of model development. Those parties have an important role to play in the value chain towards the provid
--------------------------------------------------------------------------------
Rank: 5 | Page: 24 | Score: 0.7466
Regulation should apply. For example, Article 16(2) of Regulation (EU) 2017/745, establishing that certain changes should not be considered to be modifications of a device that could affect its compliance with the applicable requirements, should continue to apply to high-risk AI systems that are medical devices within the meaning of that Regulation
--------------------------------------------------------------------------------
Rank: 6 | Page: 21 | Score: 0.7435
(72) To address concerns related to opacity and complexity of certain AI systems and help deployers to fulfil their obligations under this Regulation, transparency should be required for high-risk AI systems before they are placed on the market or put it into service. High-risk AI systems should be designed in a manner to enable deployers to unders
--------------------------------------------------------------------------------
Rank: 7 | Page: 65 | Score: 0.7381
Article 22 Authorised representatives of providers of high-risk AI systems 1. Prior to making their high-risk AI systems available on the Union market, providers established in third countries shall, by written mandate, appoint an authorised representative which is established in the Union. 2. The provider shall enable its authorised representative
--------------------------------------------------------------------------------
Rank: 8 | Page: 60 | Score: 0.7340
(v) when appropriate, its performance regarding specific persons or groups of persons on which the system is intended to be used; (vi) when appropriate, specifications for the input data, or any other relevant information in terms of the training, validation and testing data sets used, taking into account the intended purpose of the high-risk AI sy
--------------------------------------------------------------------------------
Rank: 9 | Page: 25 | Score: 0.7333
competence, in particular an adequate level of AI literacy, training and authority to properly fulfil those tasks. Those obligations should be without prejudice to other deployer obligations in relation to high-risk AI systems under Union or national law. (92) This Regulation is without prejudice to obligations for employers to inform or to inform
--------------------------------------------------------------------------------
Rank: 10 | Page: 66 | Score: 0.7324
that system, as applicable, have complied with their respective obligations as laid down in Article 16, points (b) and (c) and Article 23(3). 2. Where a distributor considers or has reason to consider, on the basis of the information in its possession, that a high-risk AI system is not in conformity with the requirements set out in Section 2, it sh
--------------------------------------------------------------------------------

In [59]:
baseline_top3 = baseline_results[:FINAL_K]

for item in baseline_top3:
    print(f"Rank {item['initial_rank']} | Page {item['page_number']}")
    print(item["text"][:500])
    print("-" * 80)

Rank 1 | Page 62
SECTION 3 Obligations of providers and deployers of high-risk AI systems and other parties Article 16 Obligations of providers of high-risk AI systems Providers of high-risk AI systems shall: (a) ensure that their high-risk AI systems are compliant with the requirements set out in Section 2; (b) indicate on the high-risk AI system or, where that is not possible, on its packaging or its accompanying documentation, as applicable, their name, registered trade name or registered trade mark, the addr
--------------------------------------------------------------------------------
Rank 2 | Page 67
Article 25 Responsibilities along the AI value chain 1. Any distributor, importer, deployer or other third-party shall be considered to be a provider of a high-risk AI system for the purposes of this Regulation and shall be subject to the obligations of the provider under Article 16, in any of the following circumstances: (a) they put their name or trademark on a high-risk AI system already placed on the market or put into service, without prejudice to contractual arrangements stipulating that t
--------------------------------------------------------------------------------
Rank 3 | Page 56
2. Where a product contains an AI system, to which the requirements of this Regulation as well as requirements of the Union harmonisation legislation listed in Section A of Annex I apply, providers shall be responsible for ensuring that their product is fully compliant with all applicable requirements under applicable Union harmonisation legislation. In ensuring the compliance of high-risk AI systems referred to in paragraph 1 with the requirements set out in this Section, and in order to ensure
--------------------------------------------------------------------------------

## Section 5 — Cross-Encoder Reranking

The Bi-Encoder compares the question and document chunks through their separately generated embeddings. The Cross-Encoder instead processes the question and each candidate chunk together, allowing it to assess their relevance more directly.

In [60]:
from sentence_transformers import CrossEncoder

reranker = CrossEncoder(
    "cross-encoder/ms-marco-MiniLM-L6-v2",
    device=DEVICE
)

print("Cross-Encoder loaded successfully.")

Loading weights:   0%|          | 0/105 [00:00<?, ?it/s]

Cross-Encoder loaded successfully.

In [61]:
def rerank_top10(query, candidates):
    pairs = [(query, candidate["text"]) for candidate in candidates]

    scores = reranker.predict(pairs)

    reranked = []

    for candidate, score in zip(candidates, scores):
        reranked.append({
            **candidate,
            "cross_score": float(score)
        })

    reranked.sort(
        key=lambda item: item["cross_score"],
        reverse=True
    )

    for rank, candidate in enumerate(reranked, start=1):
        candidate["rerank_rank"] = rank

    return reranked

In [62]:
reranked_results = rerank_top10(query, baseline_results)
reranked_top3 = reranked_results[:FINAL_K]

for item in reranked_results:
    print(
        f"New rank: {item['rerank_rank']} | "
        f"Original rank: {item['initial_rank']} | "
        f"Page: {item['page_number']} | "
        f"Cross score: {item['cross_score']:.4f}"
    )
    print(item["text"][:350])
    print("-" * 80)

New rank: 1 | Original rank: 1 | Page: 62 | Cross score: 8.0485
SECTION 3 Obligations of providers and deployers of high-risk AI systems and other parties Article 16 Obligations of providers of high-risk AI systems Providers of high-risk AI systems shall: (a) ensure that their high-risk AI systems are compliant with the requirements set out in Section 2; (b) indicate on the high-risk AI system or, where that is
--------------------------------------------------------------------------------
New rank: 2 | Original rank: 2 | Page: 67 | Cross score: 7.8999
Article 25 Responsibilities along the AI value chain 1. Any distributor, importer, deployer or other third-party shall be considered to be a provider of a high-risk AI system for the purposes of this Regulation and shall be subject to the obligations of the provider under Article 16, in any of the following circumstances: (a) they put their name or
--------------------------------------------------------------------------------
New rank: 3 | Original rank: 4 | Page: 24 | Cross score: 6.9676
services but also components or processes that are incorporated by the provider into the AI system with various objectives, including the model training, model retraining, model testing and evaluation, integration into software, or other aspects of model development. Those parties have an important role to play in the value chain towards the provid
--------------------------------------------------------------------------------
New rank: 4 | Original rank: 5 | Page: 24 | Cross score: 6.9623
Regulation should apply. For example, Article 16(2) of Regulation (EU) 2017/745, establishing that certain changes should not be considered to be modifications of a device that could affect its compliance with the applicable requirements, should continue to apply to high-risk AI systems that are medical devices within the meaning of that Regulation
--------------------------------------------------------------------------------
New rank: 5 | Original rank: 9 | Page: 25 | Cross score: 6.2195
competence, in particular an adequate level of AI literacy, training and authority to properly fulfil those tasks. Those obligations should be without prejudice to other deployer obligations in relation to high-risk AI systems under Union or national law. (92) This Regulation is without prejudice to obligations for employers to inform or to inform
--------------------------------------------------------------------------------
New rank: 6 | Original rank: 6 | Page: 21 | Cross score: 6.2112
(72) To address concerns related to opacity and complexity of certain AI systems and help deployers to fulfil their obligations under this Regulation, transparency should be required for high-risk AI systems before they are placed on the market or put it into service. High-risk AI systems should be designed in a manner to enable deployers to unders
--------------------------------------------------------------------------------
New rank: 7 | Original rank: 10 | Page: 66 | Cross score: 6.0580
that system, as applicable, have complied with their respective obligations as laid down in Article 16, points (b) and (c) and Article 23(3). 2. Where a distributor considers or has reason to consider, on the basis of the information in its possession, that a high-risk AI system is not in conformity with the requirements set out in Section 2, it sh
--------------------------------------------------------------------------------
New rank: 8 | Original rank: 7 | Page: 65 | Cross score: 5.9667
Article 22 Authorised representatives of providers of high-risk AI systems 1. Prior to making their high-risk AI systems available on the Union market, providers established in third countries shall, by written mandate, appoint an authorised representative which is established in the Union. 2. The provider shall enable its authorised representative
--------------------------------------------------------------------------------
New rank: 9 | Original rank: 3 | Page: 56 | Cross score: 5.7316
2. Where a product contains an AI system, to which the requirements of this Regulation as well as requirements of the Union harmonisation legislation listed in Section A of Annex I apply, providers shall be responsible for ensuring that their product is fully compliant with all applicable requirements under applicable Union harmonisation legislatio
--------------------------------------------------------------------------------
New rank: 10 | Original rank: 8 | Page: 60 | Cross score: 4.2118
(v) when appropriate, its performance regarding specific persons or groups of persons on which the system is intended to be used; (vi) when appropriate, specifications for the input data, or any other relevant information in terms of the training, validation and testing data sets used, taking into account the intended purpose of the high-risk AI sy
--------------------------------------------------------------------------------

In [63]:
reranked_by_id = {
    item["chunk_id"]: item for item in reranked_results
}

rank_rows = []

for item in baseline_results:
    updated = reranked_by_id[item["chunk_id"]]

    rank_rows.append({
        "chunk_id": item["chunk_id"],
        "page": item["page_number"],
        "bi_rank": item["initial_rank"],
        "cross_rank": updated["rerank_rank"],
        "rank_change": item["initial_rank"] - updated["rerank_rank"],
        "baseline_top3": item["initial_rank"] <= FINAL_K,
        "reranked_top3": updated["rerank_rank"] <= FINAL_K
    })

rank_df = pd.DataFrame(rank_rows).sort_values("cross_rank")
display(rank_df)

,chunk_id,page,bi_rank,cross_rank,rank_change,baseline_top3,reranked_top3
0,153,62,1,1,0,True,True
1,162,67,2,2,0,True,True
3,66,24,4,3,1,False,True
4,65,24,5,4,1,False,False
8,67,25,9,5,4,False,False
5,56,21,6,6,0,False,False
9,161,66,10,7,3,False,False
6,158,65,7,8,-1,False,False
2,141,56,3,9,-6,True,False
7,149,60,8,10,-2,False,False

In [64]:
baseline_top3 = baseline_results[:FINAL_K]
reranked_top3 = reranked_results[:FINAL_K]

print("BASELINE TOP 3")
for item in baseline_top3:
    print(f"Page {item['page_number']} | Chunk {item['chunk_id']}")
    print(item["text"][:300])
    print("-" * 60)

print("\nRERANKED TOP 3")
for item in reranked_top3:
    print(f"Page {item['page_number']} | Chunk {item['chunk_id']}")
    print(item["text"][:300])
    print("-" * 60)

BASELINE TOP 3
Page 62 | Chunk 153
SECTION 3 Obligations of providers and deployers of high-risk AI systems and other parties Article 16 Obligations of providers of high-risk AI systems Providers of high-risk AI systems shall: (a) ensure that their high-risk AI systems are compliant with the requirements set out in Section 2; (b) ind
------------------------------------------------------------
Page 67 | Chunk 162
Article 25 Responsibilities along the AI value chain 1. Any distributor, importer, deployer or other third-party shall be considered to be a provider of a high-risk AI system for the purposes of this Regulation and shall be subject to the obligations of the provider under Article 16, in any of the f
------------------------------------------------------------
Page 56 | Chunk 141
2. Where a product contains an AI system, to which the requirements of this Regulation as well as requirements of the Union harmonisation legislation listed in Section A of Annex I apply, providers shall be responsible for ensuring that their product is fully compliant with all applicable requiremen
------------------------------------------------------------

RERANKED TOP 3
Page 62 | Chunk 153
SECTION 3 Obligations of providers and deployers of high-risk AI systems and other parties Article 16 Obligations of providers of high-risk AI systems Providers of high-risk AI systems shall: (a) ensure that their high-risk AI systems are compliant with the requirements set out in Section 2; (b) ind
------------------------------------------------------------
Page 67 | Chunk 162
Article 25 Responsibilities along the AI value chain 1. Any distributor, importer, deployer or other third-party shall be considered to be a provider of a high-risk AI system for the purposes of this Regulation and shall be subject to the obligations of the provider under Article 16, in any of the f
------------------------------------------------------------
Page 24 | Chunk 66
services but also components or processes that are incorporated by the provider into the AI system with various objectives, including the model training, model retraining, model testing and evaluation, integration into software, or other aspects of model development. Those parties have an important
------------------------------------------------------------

## Section 6 — LLM Answer Generation

### 6.1 Initializing a Local LLM

To avoid dependency on an external API, we use a locally hosted instruction-tuned language model for answer generation. The same model is used for both the baseline and reranking pipelines to ensure a consistent comparison. Only the selected document chunks and the shared prompt are passed to the model.

In [65]:
import torch
from transformers import AutoTokenizer, AutoModelForCausalLM

LOCAL_MODEL = "Qwen/Qwen2.5-1.5B-Instruct"

tokenizer = AutoTokenizer.from_pretrained(LOCAL_MODEL)

model = AutoModelForCausalLM.from_pretrained(
    LOCAL_MODEL,
    torch_dtype=torch.float32,
    device_map="cpu"
)

model.eval()

print("Local LLM loaded successfully.")

Loading weights:   0%|          | 0/338 [00:00<?, ?it/s]

Local LLM loaded successfully.

In [66]:
def build_prompt(query, selected_chunks):
    context_parts = []

    for i, item in enumerate(selected_chunks, start=1):
        context_parts.append(
            f"[Context {i} | Page {item['page_number']} | "
            f"Chunk {item['chunk_id']}]\n{item['text']}"
        )

    context = "\n\n".join(context_parts)

    prompt = f"""
Answer the question about the EU Artificial Intelligence Act
using only the document context below.

Instructions:
1. Give a clear and accurate answer.
2. Preserve important conditions, exceptions, and role-specific obligations.
3. Do not invent legal requirements.
4. If the context is insufficient, say so.
5. Cite relevant article numbers and page numbers when identifiable.

Document context:
{context}

Question:
{query}

Answer:
"""
    return prompt

In [67]:
def generate_answer(query, selected_chunks):
    prompt = build_prompt(query, selected_chunks)

    messages = [
        {
            "role": "system",
            "content": (
                "Answer questions using only the supplied document context. "
                "Preserve important conditions and exceptions. "
                "Do not invent unsupported information. "
                "Give a concise, complete answer and finish all sentences."
            )
        },
        {
            "role": "user",
            "content": prompt
        }
    ]

    inputs = tokenizer.apply_chat_template(
        messages,
        tokenize=True,
        add_generation_prompt=True,
        return_tensors="pt",
        return_dict=True
    )

    with torch.no_grad():
        outputs = model.generate(
            **inputs,
            max_new_tokens=600,
            do_sample=False,
            pad_token_id=tokenizer.eos_token_id,
            eos_token_id=tokenizer.eos_token_id
        )

    input_length = inputs["input_ids"].shape[-1]
    new_tokens = outputs[0][input_length:]

    return tokenizer.decode(
        new_tokens,
        skip_special_tokens=True
    ).strip()

### 6.2 Generating Answers from Both Retrieval Pipelines

The same local language model and prompt template are used to generate answers from both retrieval pipelines. The baseline answer uses the Top 3 chunks selected by the Bi-Encoder, while the reranked answer uses the Top 3 chunks selected by the Cross-Encoder. This keeps the answer-generation model consistent so that differences can be analyzed in relation to the retrieved evidence.

In [68]:
query = "What obligations apply to providers of high-risk AI systems?"
answer1 = generate_answer(query, baseline_top3)
answer2 = generate_answer(query, reranked_top3)

print("ANSWER 1 — BASELINE RETRIEVAL")
print(answer1)

print("\n" + "=" * 80)

print("ANSWER 2 — CROSS-ENCODER RERANKING")
print(answer2)

ANSWER 1 — BASELINE RETRIEVAL
Providers of high-risk AI systems must:

- Ensure compliance with the requirements set out in Section 2
- Indicate their name, registered trade name, or registered trade mark, and contact details on the high-risk AI system or its packaging or accompanying documentation
- Have a quality management system in place that complies with Article 17
- Keep the documentation referred to in Article 18
- Maintain logs automatically generated by their high-risk AI systems as per Article 19
- Undertake the relevant conformity assessment procedure as per Article 43 prior to placing the system on the market or putting it into service
- Draw up an EU declaration of conformity in accordance with Article 47
- Affix the CE marking to the high-risk AI system or its packaging or accompanying documentation if not possible, indicating conformity with this Regulation
- Comply with the registration obligations referred to in Article 49(1)
- Take corrective actions and provide information as required in Article 20
- Upon a reasoned request of a national competent authority, demonstrate the conformity of the high-risk AI system with the requirements set out in Section 2
- Ensure the high-risk AI system complies with accessibility requirements in accordance with Directives (EU) 2016/2102 and (EU) 2019/882

================================================================================
ANSWER 2 — CROSS-ENCODER RERANKING
Providers of high-risk AI systems must:

1. Ensure compliance with the requirements set out in Section 2.
2. Indicate their name, registered trade name, or registered trade mark, and their contact address, on the high-risk AI system or its packaging or accompanying documentation.
3. Have a quality management system in place that complies with Article 17.
4. Keep the documentation referred to in Article 18.
5. Maintain logs automatically generated by their high-risk AI systems as per Article 19.
6. Undertake the relevant conformity assessment procedure as outlined in Article 43 prior to placing the system on the market or putting it into service.
7. Prepare an EU declaration of conformity according to Article 47.
8. Affix the CE marking if placement on the market or putting into service is involved, as per Article 48.
9. Comply with registration obligations mentioned in Article 49(1).
10. Demonstrate the system's conformity upon a reasoned request from a national competent authority, as per Article 20.
11. Ensure the system meets accessibility requirements as defined in Directives (EU) 2016/2102 and (EU) 2019/882.
12. Take corrective actions and provide requested information as needed.
13. Cooperate closely with new providers when modifying existing high-risk AI systems.
14. Provide necessary information and support to assist new providers in fulfilling their obligations.
15. Notify the initial provider of changes to the AI system's classification status if it was previously determined as non-high-risk.
16. Ensure the system complies with accessibility requirements as defined in Directives (EU) 2016/2102 and (EU) 2019/882.

In [69]:
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

with open(OUTPUT_DIR / "baseline_answer.txt", "w", encoding="utf-8") as f:
    f.write(answer1)

with open(OUTPUT_DIR / "reranked_answer.txt", "w", encoding="utf-8") as f:
    f.write(answer2)

print("Answers saved to:", OUTPUT_DIR)

Answers saved to: c:\Users\HP\Downloads\LMA_Assignment1\outputs

### 6.4 Comparing Baseline Retrieval and Cross-Encoder Reranking

We compare the initial Bi-Encoder rankings with the Cross-Encoder rankings to determine which passages enter or leave the Top 3. Rank changes help us understand whether reranking prioritizes passages that are more relevant to the query. Changes in ranking alone do not establish an improvement; the retrieved passages must also be examined for relevance and correctness.

In [70]:
import pandas as pd

reranked_by_id = {
    item["chunk_id"]: item
    for item in reranked_results
}

rank_rows = []

for item in baseline_results:
    updated = reranked_by_id[item["chunk_id"]]

    rank_rows.append({
        "chunk_id": item["chunk_id"],
        "page": item["page_number"],
        "bi_rank": item["initial_rank"],
        "cross_rank": updated["rerank_rank"],
        "rank_change": item["initial_rank"] - updated["rerank_rank"],
        "baseline_top3": item["initial_rank"] <= FINAL_K,
        "reranked_top3": updated["rerank_rank"] <= FINAL_K
    })

rank_df = pd.DataFrame(rank_rows).sort_values("cross_rank")
display(rank_df)

,chunk_id,page,bi_rank,cross_rank,rank_change,baseline_top3,reranked_top3
0,153,62,1,1,0,True,True
1,162,67,2,2,0,True,True
3,66,24,4,3,1,False,True
4,65,24,5,4,1,False,False
8,67,25,9,5,4,False,False
5,56,21,6,6,0,False,False
9,161,66,10,7,3,False,False
6,158,65,7,8,-1,False,False
2,141,56,3,9,-6,True,False
7,149,60,8,10,-2,False,False

In [71]:
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

with open(OUTPUT_DIR / "baseline_answer.txt", "w", encoding="utf-8") as f:
    f.write(answer1)

with open(OUTPUT_DIR / "reranked_answer.txt", "w", encoding="utf-8") as f:
    f.write(answer2)

rank_df.to_csv(
    OUTPUT_DIR / "ranking_comparison.csv",
    index=False
)

print("Current answers and ranking comparison saved.")

Current answers and ranking comparison saved.

### 7. Failure Mode Analysis: Stress Testing

We evaluate the retrieval pipelines using queries designed to expose weaknesses in semantic retrieval, including lexical distractors, exceptions, and negation. For each query, the Bi-Encoder retrieves ten candidate passages, and the Cross-Encoder reranks those same candidates. We inspect the Top 3 passages before and after reranking to identify whether relevant evidence is recovered.

In [72]:
stress_queries = {
    "Negation and constraints":
        "Which AI practices are prohibited under the EU AI Act, and what exceptions or conditions apply?",

    "Exceptions and corner cases":
        "Under what conditions can an AI system performing a narrow procedural or preparatory task be excluded from the high-risk classification?",

    "Similar roles / keyword trap":
        "What obligations apply to deployers of high-risk AI systems, rather than providers?"
}

stress_results = {}

for category, stress_query in stress_queries.items():
    baseline = retrieve_top10(stress_query)
    reranked = rerank_top10(stress_query, baseline)

    stress_results[category] = {
        "query": stress_query,
        "baseline": baseline,
        "reranked": reranked
    }

    print("\n" + "=" * 90)
    print("FAILURE TYPE:", category)
    print("QUERY:", stress_query)

    print("\nBASELINE TOP 3")
    for item in baseline[:FINAL_K]:
        print(
            f"Rank {item['initial_rank']} | "
            f"Page {item['page_number']} | "
            f"Chunk {item['chunk_id']}\n"
            f"{item['text'][:700]}\n"
        )

    print("\nRERANKED TOP 3")
    for item in reranked[:FINAL_K]:
        print(
            f"Rank {item['rerank_rank']} | "
            f"Page {item['page_number']} | "
            f"Chunk {item['chunk_id']}\n"
            f"{item['text'][:700]}\n"
        )

==========================================================================================
FAILURE TYPE: Negation and constraints
QUERY: Which AI practices are prohibited under the EU AI Act, and what exceptions or conditions apply?

BASELINE TOP 3
Rank 1 | Page 45 | Chunk 119
(b) prohibitions of certain AI practices; (c) specific requirements for high-risk AI systems and obligations for operators of such systems; (d) harmonised transparency rules for certain AI systems; (e) harmonised rules for the placing on the market of general-purpose AI models; (f) rules on market monitoring, market surveillance, governance and enforcement; (g) measures to support innovation, with a particular focus on SMEs, including start-ups. Article 2 Scope 1. This Regulation applies to: (a) providers placing on the market or putting into service AI systems or placing on the market general-purpose AI models in the Union, irrespective of whether those providers are established or located

Rank 2 | Page 51 | Chunk 131
Article 4 AI literacy Providers and deployers of AI systems shall take measures to ensure, to their best extent, a sufficient level of AI literacy of their staff and other persons dealing with the operation and use of AI systems on their behalf, taking into account their technical knowledge, experience, education and training and the context the AI systems are to be used in, and considering the persons or groups of persons on whom the AI systems are to be used. CHAPTER II PROHIBITED AI PRACTICES Article 5 Prohibited AI practices 1. The following AI practices shall be prohibited: (a) the placing on the market, the putting into service or the use of an AI system that deploys subliminal techniq

Rank 3 | Page 35 | Chunk 96
developing certain AI systems in the public interest within the AI regulatory sandbox, only under specified conditions, in accordance with Article 6(4) and Article 9(2), point (g), of Regulation (EU) 2016/679, and Articles 5, 6 and 10 of Regulation (EU) 2018/1725, and without prejudice to Article 4(2) and Article 10 of Directive (EU) 2016/680. All other obligations of data controllers and rights of data subjects under Regulations (EU) 2016/679 and (EU) 2018/1725 and Directive (EU) 2016/680 remain applicable. In particular, this Regulation should not provide a legal basis in the meaning of Article 22(2), point (b) of Regulation (EU) 2016/679 and Article 24(2), point (b) of Regulation (EU) 201


RERANKED TOP 3
Rank 1 | Page 51 | Chunk 131
Article 4 AI literacy Providers and deployers of AI systems shall take measures to ensure, to their best extent, a sufficient level of AI literacy of their staff and other persons dealing with the operation and use of AI systems on their behalf, taking into account their technical knowledge, experience, education and training and the context the AI systems are to be used in, and considering the persons or groups of persons on whom the AI systems are to be used. CHAPTER II PROHIBITED AI PRACTICES Article 5 Prohibited AI practices 1. The following AI practices shall be prohibited: (a) the placing on the market, the putting into service or the use of an AI system that deploys subliminal techniq

Rank 2 | Page 85 | Chunk 198
2. The obligations set out in paragraph 1, points (a) and (b), shall not apply to providers of AI models that are released under a free and open-source licence that allows for the access, usage, modification, and distribution of the model, and whose parameters, including the weights, the information on the model architecture, and the information on model usage, are made publicly available. This exception shall not apply to general-purpose AI models with systemic risks. 3. Providers of general-purpose AI models shall cooperate as necessary with the Commission and the national competent authorities in the exercise of their competences and powers pursuant to this Regulation. 4. Providers of gen

Rank 3 | Page 45 | Chunk 119
(b) prohibitions of certain AI practices; (c) specific requirements for high-risk AI systems and obligations for operators of such systems; (d) harmonised transparency rules for certain AI systems; (e) harmonised rules for the placing on the market of general-purpose AI models; (f) rules on market monitoring, market surveillance, governance and enforcement; (g) measures to support innovation, with a particular focus on SMEs, including start-ups. Article 2 Scope 1. This Regulation applies to: (a) providers placing on the market or putting into service AI systems or placing on the market general-purpose AI models in the Union, irrespective of whether those providers are established or located


==========================================================================================
FAILURE TYPE: Exceptions and corner cases
QUERY: Under what conditions can an AI system performing a narrow procedural or preparatory task be excluded from the high-risk classification?

BASELINE TOP 3
Rank 1 | Page 15 | Chunk 39
that the task performed by the AI system is intended to improve the result of a previously completed human activity that may be relevant for the purposes of the high-risk uses listed in an annex to this Regulation. Considering those characteristics, the AI system provides only an additional layer to a human activity with consequently lowered risk. That condition would, for example, apply to AI systems that are intended to improve the language used in previously drafted documents, for example in relation to professional tone, academic style of language or by aligning text to a certain brand messaging. The third condition should be that the AI system is intended to detect decision-making patte

Rank 2 | Page 15 | Chunk 40
is not high-risk on the basis of the conditions referred to above should draw up documentation of the assessment before that system is placed on the market or put into service and should provide that documentation to national competent authorities upon request. Such a provider should be obliged to register the AI system in the EU database established under this Regulation. With a view to providing further guidance for the practical implementation of the conditions under which the AI systems listed in an annex to this Regulation are, on an exceptional basis, non-high-risk, the Commission should, after consulting the Board, provide guidelines specifying that practical implementation, completed

Rank 3 | Page 60 | Chunk 149
(v) when appropriate, its performance regarding specific persons or groups of persons on which the system is intended to be used; (vi) when appropriate, specifications for the input data, or any other relevant information in terms of the training, validation and testing data sets used, taking into account the intended purpose of the high-risk AI system; (vii) where applicable, information to enable deployers to interpret the output of the high-risk AI system and use it appropriately; (c) the changes to the high-risk AI system and its performance which have been pre-determined by the provider at the moment of the initial conformity assessment, if any; (d) the human oversight measures referred


RERANKED TOP 3
Rank 1 | Page 15 | Chunk 39
that the task performed by the AI system is intended to improve the result of a previously completed human activity that may be relevant for the purposes of the high-risk uses listed in an annex to this Regulation. Considering those characteristics, the AI system provides only an additional layer to a human activity with consequently lowered risk. That condition would, for example, apply to AI systems that are intended to improve the language used in previously drafted documents, for example in relation to professional tone, academic style of language or by aligning text to a certain brand messaging. The third condition should be that the AI system is intended to detect decision-making patte

Rank 2 | Page 14 | Chunk 37
the same methodology and criteria envisaged also for any future amendments of the list of high-risk AI systems that the Commission should be empowered to adopt, via delegated acts, to take into account the rapid pace of technological development, as well as the potential changes in the use of AI systems. (53) It is also important to clarify that there may be specific cases in which AI systems referred to in pre-defined areas specified in this Regulation do not lead to a significant risk of harm to the legal interests protected under those areas because they do not materially influence the decision-making or do not harm those interests substantially. For the purposes of this Regulation, an AI

Rank 3 | Page 15 | Chunk 40
is not high-risk on the basis of the conditions referred to above should draw up documentation of the assessment before that system is placed on the market or put into service and should provide that documentation to national competent authorities upon request. Such a provider should be obliged to register the AI system in the EU database established under this Regulation. With a view to providing further guidance for the practical implementation of the conditions under which the AI systems listed in an annex to this Regulation are, on an exceptional basis, non-high-risk, the Commission should, after consulting the Board, provide guidelines specifying that practical implementation, completed


==========================================================================================
FAILURE TYPE: Similar roles / keyword trap
QUERY: What obligations apply to deployers of high-risk AI systems, rather than providers?

BASELINE TOP 3
Rank 1 | Page 62 | Chunk 153
SECTION 3 Obligations of providers and deployers of high-risk AI systems and other parties Article 16 Obligations of providers of high-risk AI systems Providers of high-risk AI systems shall: (a) ensure that their high-risk AI systems are compliant with the requirements set out in Section 2; (b) indicate on the high-risk AI system or, where that is not possible, on its packaging or its accompanying documentation, as applicable, their name, registered trade name or registered trade mark, the address at which they can be contacted; (c) have a quality management system in place which complies with Article 17; (d) keep the documentation referred to in Article 18; (e) when under their control, ke

Rank 2 | Page 67 | Chunk 162
Article 25 Responsibilities along the AI value chain 1. Any distributor, importer, deployer or other third-party shall be considered to be a provider of a high-risk AI system for the purposes of this Regulation and shall be subject to the obligations of the provider under Article 16, in any of the following circumstances: (a) they put their name or trademark on a high-risk AI system already placed on the market or put into service, without prejudice to contractual arrangements stipulating that the obligations are otherwise allocated; (b) they make a substantial modification to a high-risk AI system that has already been placed on the market or has already been put into service in such a way

Rank 3 | Page 21 | Chunk 56
(72) To address concerns related to opacity and complexity of certain AI systems and help deployers to fulfil their obligations under this Regulation, transparency should be required for high-risk AI systems before they are placed on the market or put it into service. High-risk AI systems should be designed in a manner to enable deployers to understand how the AI system works, evaluate its functionality, and comprehend its strengths and limitations. High-risk AI systems should be accompanied by appropriate information in the form of instructions of use. Such information should include the characteristics, capabilities and limitations of performance of the AI system. Those would cover informa


RERANKED TOP 3
Rank 1 | Page 62 | Chunk 153
SECTION 3 Obligations of providers and deployers of high-risk AI systems and other parties Article 16 Obligations of providers of high-risk AI systems Providers of high-risk AI systems shall: (a) ensure that their high-risk AI systems are compliant with the requirements set out in Section 2; (b) indicate on the high-risk AI system or, where that is not possible, on its packaging or its accompanying documentation, as applicable, their name, registered trade name or registered trade mark, the address at which they can be contacted; (c) have a quality management system in place which complies with Article 17; (d) keep the documentation referred to in Article 18; (e) when under their control, ke

Rank 2 | Page 67 | Chunk 162
Article 25 Responsibilities along the AI value chain 1. Any distributor, importer, deployer or other third-party shall be considered to be a provider of a high-risk AI system for the purposes of this Regulation and shall be subject to the obligations of the provider under Article 16, in any of the following circumstances: (a) they put their name or trademark on a high-risk AI system already placed on the market or put into service, without prejudice to contractual arrangements stipulating that the obligations are otherwise allocated; (b) they make a substantial modification to a high-risk AI system that has already been placed on the market or has already been put into service in such a way

Rank 3 | Page 68 | Chunk 164
2. Deployers shall assign human oversight to natural persons who have the necessary competence, training and authority, as well as the necessary support. 3. The obligations set out in paragraphs 1 and 2, are without prejudice to other deployer obligations under Union or national law and to the deployer’s freedom to organise its own resources and activities for the purpose of implementing the human oversight measures indicated by the provider. 4. Without prejudice to paragraphs 1 and 2, to the extent the deployer exercises control over the input data, that deployer shall ensure that input data is relevant and sufficiently representative in view of the intended purpose of the high-risk AI syst

In [73]:
# Inspect the relevant chunks for the failure analysis

for chunk_id in [119, 131, 198, 39, 40, 37, 153, 162, 164]:
    matches = [c for c in chunks if c["chunk_id"] == chunk_id]

    if matches:
        c = matches[0]
        print(f"\n{'=' * 80}")
        print(f"Chunk {chunk_id} | Page {c['page_number']}")
        print(c["text"])

================================================================================
Chunk 119 | Page 45
(b) prohibitions of certain AI practices; (c) specific requirements for high-risk AI systems and obligations for operators of such systems; (d) harmonised transparency rules for certain AI systems; (e) harmonised rules for the placing on the market of general-purpose AI models; (f) rules on market monitoring, market surveillance, governance and enforcement; (g) measures to support innovation, with a particular focus on SMEs, including start-ups. Article 2 Scope 1. This Regulation applies to: (a) providers placing on the market or putting into service AI systems or placing on the market general-purpose AI models in the Union, irrespective of whether those providers are established or located within the Union or in a third country; (b) deployers of AI systems that have their place of establishment or are located within the Union; (c) providers and deployers of AI systems that have their place of establishment or are located in a third country, where the output produced by the AI system is used in the Union; (d) importers and distributors of AI systems; (e) product manufacturers placing on the market or putting into service an AI system together with their product and under their own name or trademark; (f) authorised representatives of providers, which are not established in the Union; (g) affected persons that are located in the Union. 2. For AI systems classified as high-risk AI systems in accordance with Article 6(1) related to products covered by the Union harmonisation legislation listed in Section B of Annex I, only Article 6(1), Articles 102 to 109 and Article 112 apply. Article 57 applies only in so far as the requirements for high-risk AI systems under this Regulation have been integrated in that Union harmonisation legislation. 3. This Regulation does not apply to areas outside the scope of Union law, and shall not, in any event, affect the competences of the Member States concerning national security, regardless of the type of entity entrusted by the Member States with carrying out tasks in relation to those competences. This Regulation does not apply to AI systems where and in so far they are placed on the market, put into service, or used with or without modification exclusively for military, defence or national security purposes, regardless of the type of entity carrying out those activities. This Regulation does not apply to AI systems which are not placed on the market or put into service in the Union, where the output is used in the Union exclusively for military, defence or national security purposes, regardless of the type of entity carrying out those activities. 4. This Regulation applies neither to public authorities in a third country nor to international organisations falling within the scope of this Regulation pursuant to

================================================================================
Chunk 131 | Page 51
Article 4 AI literacy Providers and deployers of AI systems shall take measures to ensure, to their best extent, a sufficient level of AI literacy of their staff and other persons dealing with the operation and use of AI systems on their behalf, taking into account their technical knowledge, experience, education and training and the context the AI systems are to be used in, and considering the persons or groups of persons on whom the AI systems are to be used. CHAPTER II PROHIBITED AI PRACTICES Article 5 Prohibited AI practices 1. The following AI practices shall be prohibited: (a) the placing on the market, the putting into service or the use of an AI system that deploys subliminal techniques beyond a person’s consciousness or purposefully manipulative or deceptive techniques, with the objective, or the effect of materially distorting the behaviour of a person or a group of persons by appreciably impairing their ability to make an informed decision, thereby causing them to take a decision that they would not have otherwise taken in a manner that causes or is reasonably likely to cause that person, another person or group of persons significant harm; (b) the placing on the market, the putting into service or the use of an AI system that exploits any of the vulnerabilities of a natural person or a specific group of persons due to their age, disability or a specific social or economic situation, with the objective, or the effect, of materially distorting the behaviour of that person or a person belonging to that group in a manner that causes or is reasonably likely to cause that person or another person significant harm; (c) the placing on the market, the putting into service or the use of AI systems for the evaluation or classification of natural persons or groups of persons over a certain period of time based on their social behaviour or known, inferred or predicted personal or personality characteristics, with the social score leading to either or both of the following: (i) detrimental or unfavourable treatment of certain natural persons or groups of persons in social contexts that are unrelated to the contexts in which the data was originally generated or collected; (ii) detrimental or unfavourable treatment of certain natural persons or groups of persons that is unjustified or disproportionate to their social behaviour or its gravity; (d) the placing on the market, the putting into service for this specific purpose, or the use of an AI system for making risk assessments of natural persons in order to assess or predict the risk of a natural person committing a criminal offence, based solely on the profiling of a natural person or on assessing

================================================================================
Chunk 198 | Page 85
2. The obligations set out in paragraph 1, points (a) and (b), shall not apply to providers of AI models that are released under a free and open-source licence that allows for the access, usage, modification, and distribution of the model, and whose parameters, including the weights, the information on the model architecture, and the information on model usage, are made publicly available. This exception shall not apply to general-purpose AI models with systemic risks. 3. Providers of general-purpose AI models shall cooperate as necessary with the Commission and the national competent authorities in the exercise of their competences and powers pursuant to this Regulation. 4. Providers of general-purpose AI models may rely on codes of practice within the meaning of Article 56 to demonstrate compliance with the obligations set out in paragraph 1 of this Article, until a harmonised standard is published. Compliance with European harmonised standards grants providers the presumption of conformity to the extent that those standards cover those obligations. Providers of general-purpose AI models who do not adhere to an approved code of practice or do not comply with a European harmonised standard shall demonstrate alternative adequate means of compliance for assessment by the Commission. 5. For the purpose of facilitating compliance with Annex XI, in particular points 2 (d) and (e) thereof, the Commission is empowered to adopt delegated acts in accordance with Article 97 to detail measurement and calculation methodologies with a view to allowing for comparable and verifiable documentation. 6. The Commission is empowered to adopt delegated acts in accordance with Article 97(2) to amend Annexes XI and XII in light of evolving technological developments. 7. Any information or documentation obtained pursuant to this Article, including trade secrets, shall be treated in accordance with the confidentiality obligations set out in Article 78. Article 54 Authorised representatives of providers of general-purpose AI models 1. Prior to placing a general-purpose AI model on the Union market, providers established in third countries shall, by written mandate, appoint an authorised representative which is established in the Union. 2. The provider shall enable its authorised representative to perform the tasks specified in the mandate received from the provider. 3. The authorised representative shall perform the tasks specified in the mandate received from the provider. It shall provide a copy of the mandate to the AI Office upon request, in one of the official languages of the institutions of the Union. For the purposes of this Regulation, the mandate shall empower the authorised representative to carry out the following tasks: (a) verify that the technical documentation specified in Annex XI has been drawn up and all obligations referred to in Article 53 and, where applicable, Article 55 have been

================================================================================
Chunk 39 | Page 15
that the task performed by the AI system is intended to improve the result of a previously completed human activity that may be relevant for the purposes of the high-risk uses listed in an annex to this Regulation. Considering those characteristics, the AI system provides only an additional layer to a human activity with consequently lowered risk. That condition would, for example, apply to AI systems that are intended to improve the language used in previously drafted documents, for example in relation to professional tone, academic style of language or by aligning text to a certain brand messaging. The third condition should be that the AI system is intended to detect decision-making patterns or deviations from prior decision-making patterns. The risk would be lowered because the use of the AI system follows a previously completed human assessment which it is not meant to replace or influence, without proper human review. Such AI systems include for instance those that, given a certain grading pattern of a teacher, can be used to check ex post whether the teacher may have deviated from the grading pattern so as to flag potential inconsistencies or anomalies. The fourth condition should be that the AI system is intended to perform a task that is only preparatory to an assessment relevant for the purposes of the AI systems listed in an annex to this Regulation, thus making the possible impact of the output of the system very low in terms of representing a risk for the assessment to follow. That condition covers, inter alia, smart solutions for file handling, which include various functions from indexing, searching, text and speech processing or linking data to other data sources, or AI systems used for translation of initial documents. In any case, AI systems used in high-risk use-cases listed in an annex to this Regulation should be considered to pose significant risks of harm to the health, safety or fundamental rights if the AI system implies profiling within the meaning of Article 4, point (4) of Regulation (EU) 2016/679 or Article 3, point (4) of Directive (EU) 2016/680 or Article 3, point (5) of Regulation (EU) 2018/1725. To ensure traceability and transparency, a provider who considers that an AI system is not high-risk on the basis of the conditions referred to above should draw up documentation of the assessment before that system is placed on the market or put into service and should provide that documentation to national competent authorities upon request. Such a provider should be obliged to register the AI system in the EU database established under this Regulation. With a view to providing further guidance for the practical implementation of the conditions under which the AI systems

================================================================================
Chunk 40 | Page 15
is not high-risk on the basis of the conditions referred to above should draw up documentation of the assessment before that system is placed on the market or put into service and should provide that documentation to national competent authorities upon request. Such a provider should be obliged to register the AI system in the EU database established under this Regulation. With a view to providing further guidance for the practical implementation of the conditions under which the AI systems listed in an annex to this Regulation are, on an exceptional basis, non-high-risk, the Commission should, after consulting the Board, provide guidelines specifying that practical implementation, completed by a comprehensive list of practical examples of use cases of AI systems that are high-risk and use cases that are not. (54) As biometric data constitutes a special category of personal data, it is appropriate to classify as high-risk several critical-use cases of biometric systems, insofar as their use is permitted under relevant Union and national law. Technical inaccuracies of AI systems intended for the remote biometric identification of natural persons can lead to biased results and entail discriminatory effects. The risk of such biased results and discriminatory effects is particularly relevant with regard to age, ethnicity, race, sex or disabilities. Remote biometric identification systems should therefore be classified as high-risk in view of the risks that they pose. Such a classification excludes AI systems intended to be used for biometric verification, including authentication, the sole purpose of which is to confirm that a specific natural person is who that person claims to be and to confirm the identity of a natural person for the sole purpose of having access to a service, unlocking a device or having secure access to premises. In addition, AI systems intended to be used for biometric categorisation according to sensitive attributes or characteristics protected under Article 9(1) of Regulation (EU) 2016/679 on the basis of biometric data, in so far as these are not prohibited under this Regulation, and emotion recognition systems that are not prohibited under this Regulation, should be classified as high-risk. Biometric systems which are intended to be used solely for the purpose of enabling cybersecurity and personal data protection measures should not be considered to be high-risk AI systems. (55) As regards the management and operation of critical infrastructure, it is appropriate to classify as high-risk the AI systems intended to be used as safety components in the management and operation of critical digital infrastructure as listed in point (8) of the Annex to Directive (EU) 2022/2557, road traffic and the supply of water, gas, heating and electricity, since their failure or malfunctioning may put at risk the life and health of

================================================================================
Chunk 37 | Page 14
the same methodology and criteria envisaged also for any future amendments of the list of high-risk AI systems that the Commission should be empowered to adopt, via delegated acts, to take into account the rapid pace of technological development, as well as the potential changes in the use of AI systems. (53) It is also important to clarify that there may be specific cases in which AI systems referred to in pre-defined areas specified in this Regulation do not lead to a significant risk of harm to the legal interests protected under those areas because they do not materially influence the decision-making or do not harm those interests substantially. For the purposes of this Regulation, an AI system that does not materially influence the outcome of decision-making should be understood to be an AI system that does not have an impact on the substance, and thereby the outcome, of decision-making, whether human or automated. An AI system that does not materially influence the outcome of decision-making could include situations in which one or more of the following conditions are fulfilled. The first such condition should be that the AI system is intended to perform a narrow procedural task, such as an AI system that transforms unstructured data into structured data, an AI system that classifies incoming documents into categories or an AI system that is used to detect duplicates among a large number of applications. Those tasks are of such narrow and limited nature that they pose only limited risks which are not increased through the use of an AI system in a context that is listed as a high-risk use in an annex to this Regulation. The second condition should be EN OJ L, 12.7.2024 14/144 ELI: http://data.europa.eu/eli/reg/2024/1689/oj (30) Regulation (EU) 2018/1139 of the European Parliament and of the Council of 4 July 2018 on common rules in the field of civil aviation and establishing a European Union Aviation Safety Agency, and amending Regulations (EC) No 2111/2005, (EC) No 1008/2008, (EU) No 996/2010, (EU) No 376/2014 and Directives 2014/30/EU and 2014/53/EU of the European Parliament and of the Council, and repealing Regulations (EC) No 552/2004 and (EC) No 216/2008 of the European Parliament and of the Council and Council Regulation (EEC) No 3922/91 (OJ L 212, 22.8.2018, p. 1). (31) Regulation (EU) 2019/2144 of the European Parliament and of the Council of 27 November 2019 on type-approval requirements for motor vehicles and their trailers, and systems, components and separate technical units intended for such vehicles, as regards their general safety and the protection of vehicle occupants and vulnerable road users, amending Regulation (EU) 2018/858 of the European Parliament and of the Council and repealing Regulations (EC) No 78/2009, (EC)

================================================================================
Chunk 153 | Page 62

## Latency profiling

In [74]:
import time
import pandas as pd

def profile_query(query, repeats=5):
    # Warm-up to reduce first-run loading effects.
    candidates = retrieve_top10(query)
    rerank_top10(query, candidates)

    baseline_times = []
    reranking_times = []

    for _ in range(repeats):
        start = time.perf_counter()
        candidates = retrieve_top10(query)
        baseline_times.append(time.perf_counter() - start)

        start = time.perf_counter()
        reranked = rerank_top10(query, candidates)
        reranking_times.append(time.perf_counter() - start)

    baseline_mean = sum(baseline_times) / repeats
    reranking_mean = sum(reranking_times) / repeats

    return {
        "Query": query,
        "Baseline retrieval (s)": baseline_mean,
        "Cross-Encoder reranking (s)": reranking_mean,
        "Advanced retrieval total (s)": (
            baseline_mean + reranking_mean
        )
    }

latency_queries = [
    "What obligations apply to providers of high-risk AI systems?",
    "Which AI practices are prohibited under the EU AI Act, "
    "and what exceptions or conditions apply?",
    "What obligations apply to deployers of high-risk AI "
    "systems, rather than providers?"
]

latency_df = pd.DataFrame([profile_query(q) for q in latency_queries])

display(latency_df.round(4))

,Query,Baseline retrieval (s),Cross-Encoder reranking (s),Advanced retrieval total (s)
0,What obligations apply to providers of high-ri...,0.0313,0.4284,0.4597
1,Which AI practices are prohibited under the EU...,0.0319,0.4367,0.4686
2,What obligations apply to deployers of high-ri...,0.0320,0.4264,0.4585

In [75]:
rank_shift_rows = []

for category, result in stress_results.items():
    reranked_by_id = {
        item["chunk_id"]: item
        for item in result["reranked"]
    }

    for item in result["baseline"]:
        updated = reranked_by_id[item["chunk_id"]]

        rank_shift_rows.append({
            "Failure type": category,
            "Chunk ID": item["chunk_id"],
            "Page": item["page_number"],
            "Original rank": item["initial_rank"],
            "Reranked rank": updated["rerank_rank"],
            "Rank improvement": (
                item["initial_rank"] - updated["rerank_rank"]
            ),
            "Entered Top 3": (
                item["initial_rank"] > FINAL_K
                and updated["rerank_rank"] <= FINAL_K
            )
        })

stress_rank_df = pd.DataFrame(rank_shift_rows)

display(
    stress_rank_df.sort_values(
        ["Failure type", "Reranked rank"]
    )
)

,Failure type,Chunk ID,Page,Original rank,Reranked rank,Rank improvement,Entered Top 3
10,Exceptions and corner cases,39,15,1,1,0,False
17,Exceptions and corner cases,37,14,8,2,6,True
11,Exceptions and corner cases,40,15,2,3,-1,False
16,Exceptions and corner cases,111,41,7,4,3,False
13,Exceptions and corner cases,143,57,4,5,-1,False
19,Exceptions and corner cases,145,58,10,6,4,False
14,Exceptions and corner cases,151,61,5,7,-2,False
12,Exceptions and corner cases,149,60,3,8,-5,False
18,Exceptions and corner cases,56,21,9,9,0,False
15,Exceptions and corner cases,152,61,6,10,-4,False
1,Negation and constraints,131,51,2,1,1,False
5,Negation and constraints,198,85,6,2,4,True
0,Negation and constraints,119,45,1,3,-2,False
3,Negation and constraints,121,46,4,4,0,False
4,Negation and constraints,201,86,5,5,0,False
2,Negation and constraints,96,35,3,6,-3,False
7,Negation and constraints,261,118,8,7,1,False
9,Negation and constraints,208,90,10,8,2,False
8,Negation and constraints,50,18,9,9,0,False
6,Negation and constraints,14,6,7,10,-3,False
20,Similar roles / keyword trap,153,62,1,1,0,False
21,Similar roles / keyword trap,162,67,2,2,0,False
23,Similar roles / keyword trap,164,68,4,3,1,True
25,Similar roles / keyword trap,66,24,6,4,2,False
27,Similar roles / keyword trap,168,70,8,5,3,False
24,Similar roles / keyword trap,67,25,5,6,-1,False
22,Similar roles / keyword trap,56,21,3,7,-4,False
29,Similar roles / keyword trap,52,19,10,8,2,False
26,Similar roles / keyword trap,150,60,7,9,-2,False
28,Similar roles / keyword trap,149,60,9,10,-1,False

In [76]:
answer_comparisons = {}

for category, result in stress_results.items():
    query = result["query"]

    # Pipeline 1: Original Bi-Encoder Top 3
    baseline_top3 = sorted(
        result["baseline"],
        key=lambda item: item["initial_rank"]
    )[:FINAL_K]

    # Pipeline 2: Cross-Encoder re-ranked Top 3
    reranked_top3 = sorted(
        result["reranked"],
        key=lambda item: item["rerank_rank"]
    )[:FINAL_K]

    print("\n" + "=" * 90)
    print("FAILURE TYPE:", category)
    print("QUERY:", query)

    print("\nGENERATING BASELINE ANSWER...")
    answer1 = generate_answer(query, baseline_top3)

    print("\nGENERATING RERANKED ANSWER...")
    answer2 = generate_answer(query, reranked_top3)

    answer_comparisons[category] = {
        "query": query,
        "answer1": answer1,
        "answer2": answer2,
        "baseline_top3": baseline_top3,
        "reranked_top3": reranked_top3
    }

    print("\n--- ANSWER 1: BASELINE ---\n")
    print(answer1)

    print("\n--- ANSWER 2: RE-RANKED ---\n")
    print(answer2)

==========================================================================================
FAILURE TYPE: Negation and constraints
QUERY: Which AI practices are prohibited under the EU AI Act, and what exceptions or conditions apply?

GENERATING BASELINE ANSWER...

GENERATING RERANKED ANSWER...

--- ANSWER 1: BASELINE ---

The EU Artificial Intelligence Act prohibits the following AI practices:

1. Placing on the market, putting into service, or use of an AI system that deploys subliminal techniques beyond a person's consciousness or purposefully manipulative or deceptive techniques, with the objective, or the effect of materially distorting the behavior of a person or a group of persons by appreciably impairing their ability to make an informed decision, thereby causing them to take a decision that they would not have otherwise taken in a manner that causes or is reasonably likely to cause that person, another person or group of persons significant harm.

2. Placing on the market, putting into service or use of an AI system that exploits any of the vulnerabilities of a natural person or a specific group of persons due to their age, disability or a specific social or economic situation, with the objective, or the effect, of materially distorting the behavior of that person or a person belonging to that group in a manner that causes or is reasonably likely to cause that person or another person significant harm.

3. Placing on the market, putting into service or use of AI systems for the evaluation or classification of natural persons or groups of persons over a certain period of time based on their social behavior or known, inferred or predicted personal or personality characteristics, with the social score leading to either or both of the following:
   - Detrimental or unfavourable treatment of certain natural persons or groups of persons in social contexts that are unrelated to the contexts in which the data was originally generated or collected;
   - Detrimental or unfavourable treatment of certain natural persons or groups of persons that is unjustified or disproportionate to their social behavior or its gravity.

These prohibitions apply to high-risk AI systems, defined as those classified as such in accordance with Article 6(1). Exceptions include:

- High-risk AI systems specifically related to products covered by the Union harmonization legislation listed in Section B of Annex I, where only Articles 6(1), Articles 102 to 109 and Article 112 apply.
- AI systems where and in so far they are placed on the market, put into service, or used with or without modification exclusively for military, defense, or national security purposes, regardless of the type of entity carrying out those activities.
- AI systems which are not placed on the market or put into service in the Union, where the output is used in the Union exclusively for military, defense, or national security purposes, regardless of the type of entity carrying out those activities.

Additionally, the act does not apply to areas outside the scope of Union law, public authorities in a third country, or international organizations falling within the scope of the regulation.

--- ANSWER 2: RE-RANKED ---

The EU Artificial Intelligence Act prohibits several AI practices:

1. Placing on the market, putting into service, or using an AI system that deploys subliminal techniques beyond a person's consciousness or purposefully manipulative or deceptive techniques, with the objective or effect of materially distorting the behavior of a person or a group of persons by impairing their ability to make an informed decision, thereby causing significant harm.

2. Placing on the market, putting into service, or using an AI system that exploits any vulnerability of a natural person or a specific group of persons due to their age, disability, or specific social or economic situation, with the objective or effect of materially distorting the behavior of that person or a person belonging to that group in a manner causing significant harm.

3. Placing on the market, putting into service, or using AI systems for evaluating or classifying natural persons or groups of persons over a certain period of time based on their social behavior or known, inferred, or predicted personal or personality characteristics, resulting in detrimental or unfavourable treatment of certain natural persons or groups of persons in social contexts unrelated to the contexts in which the data was originally generated or collected, or unjustified or disproportionate treatment.

4. Placing on the market, putting into service, or using AI systems for making risk assessments of natural persons in order to assess or predict the risk of a natural person committing a criminal offense, based solely on the profiling of a natural person or assessing their social behavior or known, inferred, or predicted personal or personality characteristics.

Exceptions and conditions include:

- General-purpose AI models released under a free and open-source license that allows access, usage, modification, and distribution, provided that their parameters, including weights, information on model architecture, and information on model usage, are publicly available.

- Providers of general-purpose AI models must cooperate with the Commission and national competent authorities regarding their competences and powers.

- Providers of general-purpose AI models can rely on codes of practice to demonstrate compliance with the obligations set forth in Article 53, but if they do not adhere to an approved code of practice or do not comply with a European harmonized standard, they must demonstrate alternative adequate means of compliance.

- Information obtained through these provisions should be handled according to the confidentiality obligations outlined in Article 78.

==========================================================================================
FAILURE TYPE: Exceptions and corner cases
QUERY: Under what conditions can an AI system performing a narrow procedural or preparatory task be excluded from the high-risk classification?

GENERATING BASELINE ANSWER...

GENERATING RERANKED ANSWER...

--- ANSWER 1: BASELINE ---

An AI system performing a narrow procedural or preparatory task can be excluded from the high-risk classification if it meets the following conditions:

- It is intended to improve the result of a previously completed human activity that may be relevant for the purposes of the high-risk uses listed in an annex to this Regulation.
- It does not imply profiling within the meaning of Article 4, point (4) of Regulation (EU) 2016/679 or Article 3, point (4) of Directive (EU) 2016/680 or Article 3, point (5) of Regulation (EU) 2018/1725.
- It is not intended to replace or influence a human assessment without proper human review.
- It performs tasks only preparatory to an assessment relevant for the purposes of the AI systems listed in an annex to this Regulation, thereby minimizing the risk of representation of harm to health, safety, or fundamental rights.

--- ANSWER 2: RE-RANKED ---

An AI system performing a narrow procedural task, such as transforming unstructured data into structured data, classifying incoming documents into categories, or detecting duplicates among a large number of applications, can be excluded from the high-risk classification if it meets the following conditions:

1. **Narrow and Limited Nature**: The task must be narrowly defined and limited in scope, posing only limited risks which are not increased through the use of an AI system in a context that is listed as a high-risk use in an annex to this Regulation.

2. **Limited Impact on Outcome**: The task should not materially influence the outcome of decision-making; instead, it should focus on procedural aspects rather than substantive decisions.

Examples of such tasks might include:

- Transforming unstructured data into structured data.
- Classifying incoming documents into categories.
- Detecting duplicates among a large number of applications.

These types of tasks typically involve minimal interaction with sensitive personal data and do not significantly alter the core function of the system being assessed.

==========================================================================================
FAILURE TYPE: Similar roles / keyword trap
QUERY: What obligations apply to deployers of high-risk AI systems, rather than providers?

GENERATING BASELINE ANSWER...

GENERATING RERANKED ANSWER...

--- ANSWER 1: BASELINE ---

Deployers of high-risk AI systems must:

- Ensure that their AI systems are compliant with the requirements set out in Section 2.
- Indicate their name, registered trade name, or registered trade mark, and their contact address, on the high-risk AI system or its packaging or accompanying documentation.
- Have a quality management system in place that complies with Article 17.
- Keep the documentation referred to in Article 18.
- When under their control, keep logs automatically generated by their high-risk AI systems as referred to in Article 19.
- Ensure that the high-risk AI system undergoes the relevant conformity assessment procedure as referred to in Article 43, prior to being placed on the market or put into service.
- Draw up an EU declaration of conformity in accordance with Article 47.
- Affix the CE marking to the high-risk AI system or, where that is not possible, on its packaging or its accompanying documentation, indicating conformity with this Regulation.
- Comply with the registration obligations referred to in Article 49(1).
- Take the necessary corrective actions and provide information as required in Article 20.
- Upon a reasoned request of a national competent authority, demonstrate the conformity of the high-risk AI system with the requirements set out in Section 2.
- Ensure that the high-risk AI system complies with accessibility requirements in accordance with Directives (EU) 2016/2102 and (EU) 2019/882.

--- ANSWER 2: RE-RANKED ---

Deployers of high-risk AI systems must:

- Assign human oversight to natural persons with necessary competence, training, and authority.
- Ensure input data is relevant and sufficiently representative if the AI system is a safety component of a product covered by Union harmonization legislation.
- Monitor the operation of the high-risk AI system based on instructions for use.
- Inform providers, distributors, and market surveillance authorities of incidents promptly.
- Suspend the use of the system if there's a risk according to Article 79(1).
- Maintain logs automatically generated by the high-risk AI system for at least six months, unless otherwise provided by Union or national law.
- Keep logs as part of documentation for financial institutions subject to Union financial services law.

In [77]:
# Inspect the Top 3 passages used for each answer.

for category, result in answer_comparisons.items():
    print("\n" + "=" * 90)
    print("FAILURE TYPE:", category)
    print("QUERY:", result["query"])

    for pipeline, key in [
        ("BASELINE TOP 3", "baseline_top3"),
        ("RERANKED TOP 3", "reranked_top3")
    ]:
        print(f"\n--- {pipeline} ---")

        for item in result[key]:
            print("\nChunk ID:", item.get("chunk_id"))
            print("Page:", item.get("page_number"))
            print("Original rank:", item.get("initial_rank"))
            print("Reranked rank:", item.get("rerank_rank"))

            # Print the passage text stored in the result.
            text_fields = [
                (name, value)
                for name, value in item.items()
                if isinstance(value, str) and len(value) > 150
            ]

            if text_fields:
                for name, value in text_fields:
                    print(f"\n{name}:\n{value}")
            else:
                print("Available fields:", list(item.keys()))

==========================================================================================
FAILURE TYPE: Negation and constraints
QUERY: Which AI practices are prohibited under the EU AI Act, and what exceptions or conditions apply?

--- BASELINE TOP 3 ---

Chunk ID: 119
Page: 45
Original rank: 1
Reranked rank: None

text:
(b) prohibitions of certain AI practices; (c) specific requirements for high-risk AI systems and obligations for operators of such systems; (d) harmonised transparency rules for certain AI systems; (e) harmonised rules for the placing on the market of general-purpose AI models; (f) rules on market monitoring, market surveillance, governance and enforcement; (g) measures to support innovation, with a particular focus on SMEs, including start-ups. Article 2 Scope 1. This Regulation applies to: (a) providers placing on the market or putting into service AI systems or placing on the market general-purpose AI models in the Union, irrespective of whether those providers are established or located within the Union or in a third country; (b) deployers of AI systems that have their place of establishment or are located within the Union; (c) providers and deployers of AI systems that have their place of establishment or are located in a third country, where the output produced by the AI system is used in the Union; (d) importers and distributors of AI systems; (e) product manufacturers placing on the market or putting into service an AI system together with their product and under their own name or trademark; (f) authorised representatives of providers, which are not established in the Union; (g) affected persons that are located in the Union. 2. For AI systems classified as high-risk AI systems in accordance with Article 6(1) related to products covered by the Union harmonisation legislation listed in Section B of Annex I, only Article 6(1), Articles 102 to 109 and Article 112 apply. Article 57 applies only in so far as the requirements for high-risk AI systems under this Regulation have been integrated in that Union harmonisation legislation. 3. This Regulation does not apply to areas outside the scope of Union law, and shall not, in any event, affect the competences of the Member States concerning national security, regardless of the type of entity entrusted by the Member States with carrying out tasks in relation to those competences. This Regulation does not apply to AI systems where and in so far they are placed on the market, put into service, or used with or without modification exclusively for military, defence or national security purposes, regardless of the type of entity carrying out those activities. This Regulation does not apply to AI systems which are not placed on the market or put into service in the Union, where the output is used in the Union exclusively for military, defence or national security purposes, regardless of the type of entity carrying out those activities. 4. This Regulation applies neither to public authorities in a third country nor to international organisations falling within the scope of this Regulation pursuant to

Chunk ID: 131
Page: 51
Original rank: 2
Reranked rank: None

text:
Article 4 AI literacy Providers and deployers of AI systems shall take measures to ensure, to their best extent, a sufficient level of AI literacy of their staff and other persons dealing with the operation and use of AI systems on their behalf, taking into account their technical knowledge, experience, education and training and the context the AI systems are to be used in, and considering the persons or groups of persons on whom the AI systems are to be used. CHAPTER II PROHIBITED AI PRACTICES Article 5 Prohibited AI practices 1. The following AI practices shall be prohibited: (a) the placing on the market, the putting into service or the use of an AI system that deploys subliminal techniques beyond a person’s consciousness or purposefully manipulative or deceptive techniques, with the objective, or the effect of materially distorting the behaviour of a person or a group of persons by appreciably impairing their ability to make an informed decision, thereby causing them to take a decision that they would not have otherwise taken in a manner that causes or is reasonably likely to cause that person, another person or group of persons significant harm; (b) the placing on the market, the putting into service or the use of an AI system that exploits any of the vulnerabilities of a natural person or a specific group of persons due to their age, disability or a specific social or economic situation, with the objective, or the effect, of materially distorting the behaviour of that person or a person belonging to that group in a manner that causes or is reasonably likely to cause that person or another person significant harm; (c) the placing on the market, the putting into service or the use of AI systems for the evaluation or classification of natural persons or groups of persons over a certain period of time based on their social behaviour or known, inferred or predicted personal or personality characteristics, with the social score leading to either or both of the following: (i) detrimental or unfavourable treatment of certain natural persons or groups of persons in social contexts that are unrelated to the contexts in which the data was originally generated or collected; (ii) detrimental or unfavourable treatment of certain natural persons or groups of persons that is unjustified or disproportionate to their social behaviour or its gravity; (d) the placing on the market, the putting into service for this specific purpose, or the use of an AI system for making risk assessments of natural persons in order to assess or predict the risk of a natural person committing a criminal offence, based solely on the profiling of a natural person or on assessing

Chunk ID: 96
Page: 35
Original rank: 3
Reranked rank: None

text:
developing certain AI systems in the public interest within the AI regulatory sandbox, only under specified conditions, in accordance with Article 6(4) and Article 9(2), point (g), of Regulation (EU) 2016/679, and Articles 5, 6 and 10 of Regulation (EU) 2018/1725, and without prejudice to Article 4(2) and Article 10 of Directive (EU) 2016/680. All other obligations of data controllers and rights of data subjects under Regulations (EU) 2016/679 and (EU) 2018/1725 and Directive (EU) 2016/680 remain applicable. In particular, this Regulation should not provide a legal basis in the meaning of Article 22(2), point (b) of Regulation (EU) 2016/679 and Article 24(2), point (b) of Regulation (EU) 2018/1725. Providers and prospective OJ L, 12.7.2024 EN ELI: http://data.europa.eu/eli/reg/2024/1689/oj 35/144

--- RERANKED TOP 3 ---

Chunk ID: 131
Page: 51
Original rank: 2
Reranked rank: 1

text:
Article 4 AI literacy Providers and deployers of AI systems shall take measures to ensure, to their best extent, a sufficient level of AI literacy of their staff and other persons dealing with the operation and use of AI systems on their behalf, taking into account their technical knowledge, experience, education and training and the context the AI systems are to be used in, and considering the persons or groups of persons on whom the AI systems are to be used. CHAPTER II PROHIBITED AI PRACTICES Article 5 Prohibited AI practices 1. The following AI practices shall be prohibited: (a) the placing on the market, the putting into service or the use of an AI system that deploys subliminal techniques beyond a person’s consciousness or purposefully manipulative or deceptive techniques, with the objective, or the effect of materially distorting the behaviour of a person or a group of persons by appreciably impairing their ability to make an informed decision, thereby causing them to take a decision that they would not have otherwise taken in a manner that causes or is reasonably likely to cause that person, another person or group of persons significant harm; (b) the placing on the market, the putting into service or the use of an AI system that exploits any of the vulnerabilities of a natural person or a specific group of persons due to their age, disability or a specific social or economic situation, with the objective, or the effect, of materially distorting the behaviour of that person or a person belonging to that group in a manner that causes or is reasonably likely to cause that person or another person significant harm; (c) the placing on the market, the putting into service or the use of AI systems for the evaluation or classification of natural persons or groups of persons over a certain period of time based on their social behaviour or known, inferred or predicted personal or personality characteristics, with the social score leading to either or both of the following: (i) detrimental or unfavourable treatment of certain natural persons or groups of persons in social contexts that are unrelated to the contexts in which the data was originally generated or collected; (ii) detrimental or unfavourable treatment of certain natural persons or groups of persons that is unjustified or disproportionate to their social behaviour or its gravity; (d) the placing on the market, the putting into service for this specific purpose, or the use of an AI system for making risk assessments of natural persons in order to assess or predict the risk of a natural person committing a criminal offence, based solely on the profiling of a natural person or on assessing

Chunk ID: 198
Page: 85
Original rank: 6
Reranked rank: 2

text:
2. The obligations set out in paragraph 1, points (a) and (b), shall not apply to providers of AI models that are released under a free and open-source licence that allows for the access, usage, modification, and distribution of the model, and whose parameters, including the weights, the information on the model architecture, and the information on model usage, are made publicly available. This exception shall not apply to general-purpose AI models with systemic risks. 3. Providers of general-purpose AI models shall cooperate as necessary with the Commission and the national competent authorities in the exercise of their competences and powers pursuant to this Regulation. 4. Providers of general-purpose AI models may rely on codes of practice within the meaning of Article 56 to demonstrate compliance with the obligations set out in paragraph 1 of this Article, until a harmonised standard is published. Compliance with European harmonised standards grants providers the presumption of conformity to the extent that those standards cover those obligations. Providers of general-purpose AI models who do not adhere to an approved code of practice or do not comply with a European harmonised standard shall demonstrate alternative adequate means of compliance for assessment by the Commission. 5. For the purpose of facilitating compliance with Annex XI, in particular points 2 (d) and (e) thereof, the Commission is empowered to adopt delegated acts in accordance with Article 97 to detail measurement and calculation methodologies with a view to allowing for comparable and verifiable documentation. 6. The Commission is empowered to adopt delegated acts in accordance with Article 97(2) to amend Annexes XI and XII in light of evolving technological developments. 7. Any information or documentation obtained pursuant to this Article, including trade secrets, shall be treated in accordance with the confidentiality obligations set out in Article 78. Article 54 Authorised representatives of providers of general-purpose AI models 1. Prior to placing a general-purpose AI model on the Union market, providers established in third countries shall, by written mandate, appoint an authorised representative which is established in the Union. 2. The provider shall enable its authorised representative to perform the tasks specified in the mandate received from the provider. 3. The authorised representative shall perform the tasks specified in the mandate received from the provider. It shall provide a copy of the mandate to the AI Office upon request, in one of the official languages of the institutions of the Union. For the purposes of this Regulation, the mandate shall empower the authorised representative to carry out the following tasks: (a) verify that the technical documentation specified in Annex XI has been drawn up and all obligations referred to in Article 53 and, where applicable, Article 55 have been

Chunk ID: 119
Page: 45
Original rank: 1
Reranked rank: 3

text:
(b) prohibitions of certain AI practices; (c) specific requirements for high-risk AI systems and obligations for operators of such systems; (d) harmonised transparency rules for certain AI systems; (e) harmonised rules for the placing on the market of general-purpose AI models; (f) rules on market monitoring, market surveillance, governance and enforcement; (g) measures to support innovation, with a particular focus on SMEs, including start-ups. Article 2 Scope 1. This Regulation applies to: (a) providers placing on the market or putting into service AI systems or placing on the market general-purpose AI models in the Union, irrespective of whether those providers are established or located within the Union or in a third country; (b) deployers of AI systems that have their place of establishment or are located within the Union; (c) providers and deployers of AI systems that have their place of establishment or are located in a third country, where the output produced by the AI system is used in the Union; (d) importers and distributors of AI systems; (e) product manufacturers placing on the market or putting into service an AI system together with their product and under their own name or trademark; (f) authorised representatives of providers, which are not established in the Union; (g) affected persons that are located in the Union. 2. For AI systems classified as high-risk AI systems in accordance with Article 6(1) related to products covered by the Union harmonisation legislation listed in Section B of Annex I, only Article 6(1), Articles 102 to 109 and Article 112 apply. Article 57 applies only in so far as the requirements for high-risk AI systems under this Regulation have been integrated in that Union harmonisation legislation. 3. This Regulation does not apply to areas outside the scope of Union law, and shall not, in any event, affect the competences of the Member States concerning national security, regardless of the type of entity entrusted by the Member States with carrying out tasks in relation to those competences. This Regulation does not apply to AI systems where and in so far they are placed on the market, put into service, or used with or without modification exclusively for military, defence or national security purposes, regardless of the type of entity carrying out those activities. This Regulation does not apply to AI systems which are not placed on the market or put into service in the Union, where the output is used in the Union exclusively for military, defence or national security purposes, regardless of the type of entity carrying out those activities. 4. This Regulation applies neither to public authorities in a third country nor to international organisations falling within the scope of this Regulation pursuant to

==========================================================================================
FAILURE TYPE: Exceptions and corner cases
QUERY: Under what conditions can an AI system performing a narrow procedural or preparatory task be excluded from the high-risk classification?

--- BASELINE TOP 3 ---

Chunk ID: 39
Page: 15
Original rank: 1
Reranked rank: None

text:
that the task performed by the AI system is intended to improve the result of a previously completed human activity that may be relevant for the purposes of the high-risk uses listed in an annex to this Regulation. Considering those characteristics, the AI system provides only an additional layer to a human activity with consequently lowered risk. That condition would, for example, apply to AI systems that are intended to improve the language used in previously drafted documents, for example in relation to professional tone, academic style of language or by aligning text to a certain brand messaging. The third condition should be that the AI system is intended to detect decision-making patterns or deviations from prior decision-making patterns. The risk would be lowered because the use of the AI system follows a previously completed human assessment which it is not meant to replace or influence, without proper human review. Such AI systems include for instance those that, given a certain grading pattern of a teacher, can be used to check ex post whether the teacher may have deviated from the grading pattern so as to flag potential inconsistencies or anomalies. The fourth condition should be that the AI system is intended to perform a task that is only preparatory to an assessment relevant for the purposes of the AI systems listed in an annex to this Regulation, thus making the possible impact of the output of the system very low in terms of representing a risk for the assessment to follow. That condition covers, inter alia, smart solutions for file handling, which include various functions from indexing, searching, text and speech processing or linking data to other data sources, or AI systems used for translation of initial documents. In any case, AI systems used in high-risk use-cases listed in an annex to this Regulation should be considered to pose significant risks of harm to the health, safety or fundamental rights if the AI system implies profiling within the meaning of Article 4, point (4) of Regulation (EU) 2016/679 or Article 3, point (4) of Directive (EU) 2016/680 or Article 3, point (5) of Regulation (EU) 2018/1725. To ensure traceability and transparency, a provider who considers that an AI system is not high-risk on the basis of the conditions referred to above should draw up documentation of the assessment before that system is placed on the market or put into service and should provide that documentation to national competent authorities upon request. Such a provider should be obliged to register the AI system in the EU database established under this Regulation. With a view to providing further guidance for the practical implementation of the conditions under which the AI systems

Chunk ID: 40
Page: 15
Original rank: 2
Reranked rank: None

text: